import os


TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
OPENWEATHERMAP_API_KEY = os.getenv("OPENWEATHERMAP_API_KEY")
GEONAMES_API_KEY = os.getenv("GEONAMES_API_KEY")

TELEGA_DB_NAME = os.getenv("TELEGA_DB_NAME")
TELEGA_DB_USER = os.getenv("TELEGA_DB_USER")
TELEGA_DB_PASS = os.getenv("TELEGA_DB_PASS")
TELEGA_DB_HOST = os.getenv("TELEGA_DB_HOST")
TELEGA_DB_PORT = os.getenv("TELEGA_DB_PORT")